<a href="https://colab.research.google.com/github/PoojaDasIndia/Practices-Code/blob/main/100_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('numpy-100-exercises')
jovian.set_colab_id('1j9mWt-QJ5s8jUX_ehG8eaqn5pkUdEiuu')

# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/100-numpy-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/100-numpy-exercises


'https://jovian.ai/poojadas2014-pd/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [ ]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

print(np.show_config())

1.20.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# a.size give size of array
size_of_array = null_vector.size

# a.itemsize give memory size of  one element of  array
size_of_one_element = null_vector.itemsize

print("Size of array :",size_of_array)
print("Memory size of one element in byten:",size_of_one_element )


# memory size of array = size of array * one  memoery element of array

print("Memory size of array :",size_of_array*size_of_one_element)

Size of array : 10
Memory size of one element in byten: 8
Memory size of array : 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.add.__doc__)      # np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:

null_vector=np.zeros(10)
print("Null vector : \n",null_vector)


null_vector[4]=1
print("\nAfter update null vector fifth value with 1 :\n",null_vector)

Null vector : 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

After update null vector fifth value with 1 :
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr= np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr=np.arange(0,9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = [1,2,0,0,4,0]
  
print ("Input  list array : \n", arr)
    
print ("Indices of non zero elements : ", np.nonzero(arr)) 


Input  list array : 
 [1, 2, 0, 0, 4, 0]
Indices of non zero elements :  (array([0, 1, 4]),)


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
arr=np.ones((3,3),dtype=int)
print("Identity Matrix (3 x 3):\n" ,arr)

Identity Matrix (3 x 3):
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr=np.random.random((3,3,3))
print("Random Matrix of value 5 (3 x 3 x 3):\n" ,arr)

Random Matrix of value 5 (3 x 3 x 3):
 [[[0.3684323  0.02985175 0.21678859]
  [0.5474189  0.93503511 0.19409405]
  [0.29749674 0.25717882 0.41489788]]

 [[0.51543425 0.92792879 0.95480836]
  [0.55875593 0.67026352 0.70604481]
  [0.4022337  0.55809057 0.95038763]]

 [[0.03601437 0.6140905  0.38361269]
  [0.91582105 0.68895687 0.61413313]
  [0.04221126 0.65200738 0.60357786]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr=np.random.random((10,10))
print("Minimum : ", np.min(arr))
print("Maximum : ", np.max(arr))

Minimum :  0.0076652276603323966
Maximum :  0.9911399866296349


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
vector = np.random.random(30)
print("Mean of Vector size 30 :", np.mean(vector) )

Mean of Vector size 30 : 0.5526481814408848


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr=np.ones((5,5),dtype=int)
print("Array :\n",arr)

arr[1:-1,1:-1] =0
print("\n\n1 on the border and 0 inside in the array:\n",arr)


Array :
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


1 on the border and 0 inside in the array:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
print("Existing Array : \n", arr)

arr= np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

Existing Array : 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr=np.diag([1,2,3,4],k = -1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr=np.ones((8,8),dtype=int)
arr[0::2,0::2]=0
arr[1::2,1::2]=0
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8),order="C"))

(1, 5, 4)


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr=np.array([[0,1],[1,0]])
arr=np.tile(arr,(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr=np.random.random((5,5))
print("Array :\n\n",arr)

Max,Min=np.max(arr),np.min(arr)

arr= (arr-Min)/(Max-Min)

print("\nNormalized Array :\n\n",arr)


Array :

 [[0.27398766 0.95543026 0.00306311 0.16409855 0.39998878]
 [0.37209456 0.76981201 0.48800611 0.46549872 0.78442834]
 [0.57886639 0.42791233 0.17661446 0.38153953 0.63806394]
 [0.48946923 0.79178387 0.41586525 0.56479    0.42590507]
 [0.62821637 0.99452132 0.49141586 0.18968653 0.32763291]]

Normalized Array :

 [[0.27325867 0.96057216 0.         0.16242282 0.40034534]
 [0.37221079 0.77335473 0.48912097 0.46641967 0.78809699]
 [0.58076405 0.42850946 0.17504656 0.38173714 0.64047161]
 [0.49059669 0.79551589 0.41635858 0.56656639 0.4264849 ]
 [0.63053919 1.         0.49256009 0.18823125 0.32736609]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['blue'])
print(color,type(color))
color

4
(1, 2, 4, 3) <class 'numpy.ndarray'>


array((1, 2, 4, 3),
      dtype=[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
arr1=np.random.randint(5,10,(5,3))
arr2=np.random.randint(4,15,(3,2))
print(arr1@arr2)

[[118 138]
 [159 174]
 [105 118]
 [133 154]
 [125 140]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(11)

arr[(arr>=3) & (arr<= 8)]*= -1

print(arr)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5)))
from numpy import *
print(sum(range(5),-1))

10
10


In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = arange(10)
print("Z**Z :",Z**Z)
print("\n2 << Z >> 2 :",2 << Z >> 2)
print("\nZ <- Z :",Z <- Z)   
print("\n1j*Z : ",1j*Z)
print("\nZ/1/1 : ",Z/1/1)
print("Z<Z>Z : ", Z<Z>Z)

Z**Z : [        1         1         4        27       256      3125     46656
    823543  16777216 387420489]

2 << Z >> 2 : [  0   1   2   4   8  16  32  64 128 256]

Z <- Z : [False False False False False False False False False False]

1j*Z :  [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]

Z/1/1 :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))

nan


/tmp/ipykernel_206/4120864939.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


In [ ]:
print(np.array(0) // np.array(0))

0


/tmp/ipykernel_206/4108562882.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [ ]:


print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr=np.random.random((3,3))
arr=np.round(arr,2)
print(arr)

[[0.13 0.48 0.86]
 [0.31 0.47 0.78]
 [0.98 0.77 0.18]]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1=np.random.randint(1,20,10)

arr2= np.random.randint(5,10,10)

print(np.intersect1d(arr1,arr2))

[6 7 8]


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today     = np.datetime64('today', 'D')
day=np.timedelta64(1,"D")

print("Yesterday : ",today-day)
print("Today : ",today)
print("Tomorrow : ",today+day)

Yesterday :  2022-06-29
Today :  2022-06-30
Tomorrow :  2022-07-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*5
B = np.ones(3)*4

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print(A@B)

-67.5


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.uniform(1,10,5)
print(arr)
print(floor(arr))
print(arr.astype(int))
print(np.ceil(arr)-1)
print(arr -arr%1)


[2.6671529  4.33557023 2.34745005 3.68499994 5.87981118]
[2. 4. 2. 3. 5.]
[2 4 2 3 5]
[2. 4. 2. 3. 5.]
[2. 4. 2. 3. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr=np.ones((5,5),dtype=int)
a=np.arange(5)
arr=arr*a
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def gen ():
    for i in range(10):
        yield i

arr=np.fromiter(gen(),dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr=np.linspace(0,1,10,endpoint=False)
arr[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr=np.random.randint(1,10,10)
print(arr)
print(np.sort(arr))

[3 4 5 5 9 6 1 4 8 9]
[1 3 4 4 5 5 6 8 9 9]


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
print(arr)
print("Sum : ",sum(arr))

[3 4 5 5 9 6 1 4 8 9]
Sum :  54


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
arr1=np.random.randint(1,10,10)
print("Array first : ",arr1)
arr2=np.random.randint(1,10,10)
print("Array Second : ",arr2)

print(np.array_equal(arr1,arr2))

Array first :  [9 3 7 6 2 5 7 6 2 7]
Array Second :  [4 6 7 4 7 1 8 3 1 2]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
print(arr1)
arr1.flags.writeable=False

arr1[2]=45

[9 3 7 6 2 5 7 6 2 7]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[0.63858761 0.38184894]
 [0.92306513 1.06097268]
 [0.35256791 0.32888686]
 [0.94293851 0.37554531]
 [0.89880315 1.0610938 ]
 [0.19130784 0.18327627]
 [0.97518375 1.0677384 ]
 [1.02534473 0.42212542]
 [0.79288285 0.85442042]
 [0.95152204 0.84208732]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr=np.random.randint(1,10,10)
print("Array first : ",arr)
arr[arr.argmax()]=0
print(arr)

Array first :  [3 2 4 5 4 7 4 8 7 1]
[3 2 4 5 4 7 4 0 7 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-100-exercises" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-100-exercises


'https://jovian.ai/poojadas2014-pd/numpy-100-exercises'

Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100