<a href="https://colab.research.google.com/github/PoojaDasIndia/Practices-Code/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('numpy-array-operations')
jovian.set_colab_id('11STA9prMxQvnRtCU_tnoM39KzYF3rCNC')

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-array-operations


'https://jovian.ai/poojadas2014-pd/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

# List of functions explained 
    function1 = np.add
    function2 = np.power
    function3 = np.dot
    function4 = np.multiple
    function5 = np.hstack

## Function 1 - np.add

np.add() used to add element of  two or more array .

In [ ]:
# Example 1 - working 
arr1 = [[1, 2], 
        [3, 4.]]

np.add(arr1,2)

array([[3., 4.],
       [5., 6.]])

### Explanation about example
> First input array which is `arr` in which 2 will be added.

     like   | 1 + 2   2 + 2|
            | 3 + 2    .4 + 2|

In [ ]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [8, 9]]

np.add(arr1,arr2)

array([[ 6.,  8.],
       [11., 13.]])

### Explanation about example
> First input array in  which  element of  `arr1`  is added with element of `arr2` 
    
    like | 1 + 5   2 + 6|
          | 3 + 8   4 + 9|


In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.add(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### Explanation about example (why it breaks and how to fix it)

For doing np.add() we need same size of array element in both array than only we can do np.add()


#### how to fix it

If we vertically stack  zeroes  than we can do it.like

In [ ]:
# to fix it

arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

print("Before Modifing lists\n\n")

print("List 1: \n",arr1)

print("\nlList 2:",arr2)


# change list to array
arr1 =np.array(arr1)
arr2 =np.array(arr2)

print(f"Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n")

arr=np.zeros((1,2),dtype=int)
arr1=np.vstack((arr1,arr))

print("\n\nAfter Modifing lists\n\n")
print("array 1:\n",arr1)

# reshape Array2

arr2=arr2.reshape(3,2)
print("\n\narray 2:",arr2)

print(f"\nAfter Stack Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n\n")

print (np.add(arr1,arr2) )

Before Modifing lists


List 1: 
 [[1, 2], [3, 4.0]]

lList 2: [[5, 6, 7], [8, 9, 10]]
Shape of array 1 :(2, 2)
Shape of array 2 :(2, 3)



After Modifing lists


array 1:
 [[1. 2.]
 [3. 4.]
 [0. 0.]]


array 2: [[ 5  6]
 [ 7  8]
 [ 9 10]]

After Stack Shape of array 1 :(3, 2)
Shape of array 2 :(3, 2)


[[ 6.  8.]
 [10. 12.]
 [ 9. 10.]]


Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-array-operations


'https://jovian.ai/poojadas2014-pd/numpy-array-operations'

## Function 2 - np.power

In this Function the first input array as base and returns it raised to the power of the corresponding element in the second input array.

In [ ]:
# Example 1 - working
arr = [[10, 2], 
        [3, 4]]

print (np.power(arr,2) )

[[100   4]
 [  9  16]]


### Explanation about example
> First input array which is `arr` work as power's function first parameter which is base element and the 2 is work  as  Exponent &  functions second parameter .In this each element in array have power with  2.

     like   | 10 power 2   2 power 2|
            | 3 power 2    4 power 2|

In [ ]:
# Example 2 - working

arr1 = [[10, 2], 
        [3, 4]]

arr2 = [[2, 2], 
        [3, 4]]

print (np.power(arr1,arr2) )

[[100   4]
 [ 27 256]]


### Explanation about example
> First input array which is `arr1` work as power's function first parameter which is base element and the array `arr2` is work as Exponent & functions second parameter .In this each element in arr1 have power with each element in arr2.

     like | 10 power 2   2 power 2|
          | 3 power 3    4 power 4|


In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[10, 2], 
        [3, 4]]

arr2 = [[2, 2,7], 
        [3, 4,6]]

print (np.power(arr1,arr2) )

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### Explanation about example (why it breaks and how to fix it)

For doing np.power() we need same size of array element in both array than only we can do np.power()


#### how to fix it

If we vertically stack  zeroes  than we can do it.like


In [ ]:
# to fix it

arr1 = [[10, 2], 
        [3, 4]]

arr2 = [[2, 2,7], 
        [3, 4,6]]

print("Before Modifing lists\n\n")

print("List 1: \n",arr1)

print("\nlList 2:",arr2)


# change list to array
arr1 =np.array(arr1)
arr2 =np.array(arr2)

print(f"Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n")

arr=np.zeros((1,2),dtype=int)
arr1=np.vstack((arr1,arr))

print("\n\nAfter Modifing lists\n\n")
print("array 1:\n",arr1)

# reshape Array2

arr2=arr2.reshape(3,2)
print("\n\narray 2:",arr2)

print(f"\nAfter Stack Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n\n")

print (np.power(arr1,arr2) )

Before Modifing lists


List 1: 
 [[10, 2], [3, 4]]

lList 2: [[2, 2, 7], [3, 4, 6]]
Shape of array 1 :(2, 2)
Shape of array 2 :(2, 3)



After Modifing lists


array 1:
 [[10  2]
 [ 3  4]
 [ 0  0]]


array 2: [[2 2]
 [7 3]
 [4 6]]

After Stack Shape of array 1 :(3, 2)
Shape of array 2 :(3, 2)


[[ 100    4]
 [2187   64]
 [   0    0]]


Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-array-operations


'https://jovian.ai/poojadas2014-pd/numpy-array-operations'

## Function 3 - np.dot

For N-dimensional arrays, it is a sum product over the last axis of a and the second-last axis of b.

In [ ]:
# Example 1 - working
arr = [[10, 2], 
        [3, 4]]

print (np.dot(arr,2) )

[[20  4]
 [ 6  8]]


### Explanation about example
> First input array in  which  element of  `arr`  is multiply  with 2 
    
    like  | 10 * 2   2 * 2|
          | 3 * 2    4 * 2|


In [ ]:
# Example 2 - working
arr1 = [[10, 2], 
        [3, 4]]

arr2 = [[2, 2], 
        [3, 4]]

print (np.dot(arr1,arr2) )

print(3*2+4*4)

[[26 28]
 [18 22]]
22


### Explanation about example
>It is sum of product , sum of  element of  `arr1`  is multiply with element of `arr2` 
    
    like | 10*2+2*3   10*2+2*4 |
         | 3*2+4*3     3*2+4*4 |

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[10, 2], 
        [3, 4]]

arr2 = [[2, 2], 
        [3, 4],
        [5, 7]]

print (np.dot(arr1,arr2) )

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

### Explanation about example (why it breaks and how to fix it)

For doing np.dot() we need same size of array element N X M and second M X N  , size of row should be  same col. of other array.


#### how to fix it

If we  transpose  or reshape it by(2,3) array  than we can do it.like

In [ ]:
arr1 = [[10, 2], 
        [3, 4]]

arr2 = [[2, 2], 
        [3, 4],
        [5, 7]]


print("Before Modifing lists\n\n")

print("List 1: \n",arr1)

print("\nlList 2:",arr2)


# change list to array
arr1 =np.array(arr1)
arr2 =np.array(arr2)  
print(f"Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n")


# transpose

arr2=arr2.T

print("\n\nAfter Modifing lists\n\n")
print("array 1:\n",arr1)

# reshape Array2

print("\n\narray 2:",arr2)

print(f"\nAfter Stack Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n\n")



print (np.dot(arr1,arr2) )

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 4 - np.multiply

used to multiply the element in array.

In [ ]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

np.multiply(arr1,2)

### Explanation about example
> First input array which is `arr` in which 2 will be multiple.

     like   | 1 * 2   2 * 2|
            | 3 * 2    .4 * 2|

In [ ]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [8, 9]]

np.multiply(arr1,arr2)

array([[ 5., 12.],
       [24., 36.]])

### Explanation about example
> First input array in  which  element of  `arr1`  is multiple with element of `arr2` 
    
    like | 1 * 5   2 * 6|
          | 3 * 8   4 * 9|

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.multiply(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### Explanation about example (why it breaks and how to fix it)

For doing np.multiply() we need same size of array element in both array than only we can do np.multiple()


#### how to fix it

If we vertically stack  ones  than we can do it.like

In [ ]:
# to fix it

arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

print("Before Modifing lists\n\n")

print("List 1: \n",arr1)

print("\nlList 2:",arr2)


# change list to array
arr1 =np.array(arr1)
arr2 =np.array(arr2)

print(f"Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n")

arr=np.ones((1,2),dtype=int)
arr1=np.vstack((arr1,arr))

print("\n\nAfter Modifing lists\n\n")
print("array 1:\n",arr1)

# reshape Array2

arr2=arr2.reshape(3,2)
print("\n\narray 2:",arr2)

print(f"\nAfter Stack Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n\n")

print (np.multiply(arr1,arr2) )

Before Modifing lists


List 1: 
 [[1, 2], [3, 4.0]]

lList 2: [[5, 6, 7], [8, 9, 10]]
Shape of array 1 :(2, 2)
Shape of array 2 :(2, 3)



After Modifing lists


array 1:
 [[1. 2.]
 [3. 4.]
 [1. 1.]]


array 2: [[ 5  6]
 [ 7  8]
 [ 9 10]]

After Stack Shape of array 1 :(3, 2)
Shape of array 2 :(3, 2)


[[ 5. 12.]
 [21. 32.]
 [ 9. 10.]]


Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-array-operations


'https://jovian.ai/poojadas2014-pd/numpy-array-operations'

## Function 5 - np.hstack

used to concentrate two  array  horizontally 

In [ ]:
# Example 1 - working
arr1=np.arange(5)
arr2=np.arange(6,11)
print(np.hstack((arr1,arr2)))

[ 0  1  2  3  4  6  7  8  9 10]


### Explanation about example

 vector arr1 is concentrate  vector arr2  horizontally

In [ ]:
# Example 2 - working

arr1=np.arange(6).reshape(2,3)
arr2=np.arange(7,13).reshape(2,3)
print(np.hstack((arr1,arr2)))

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


### Explanation about example
array arr1 is concentrate  array arr2  horizontally

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(7,13).reshape(3,2)
print(np.hstack((arr1,arr2)))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

### Explanation about example (why it breaks and how to fix it)

For doing np.hstack() we need same size of array element in both array 

#### how to fix it

If we transpose one array  than we can do it.like

In [ ]:
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(7,13).reshape(3,2)

print(f"Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n")


# transpose

arr2=arr2.T

print("\n\nAfter Transpose \n\n")
print("array 1:\n",arr1)

# reshape Array2

print("\n\narray 2:",arr2)

print(f"\nAfter Stack Shape of array 1 :{arr1.shape}\nShape of array 2 :{arr2.shape}\n\n")



print (np.hstack((arr1,arr2)))

Shape of array 1 :(2, 3)
Shape of array 2 :(3, 2)



After Transpose 


array 1:
 [[0 1 2]
 [3 4 5]]


array 2: [[ 7  9 11]
 [ 8 10 12]]

After Stack Shape of array 1 :(2, 3)
Shape of array 2 :(2, 3)


[[ 0  1  2  7  9 11]
 [ 3  4  5  8 10 12]]


Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-array-operations


'https://jovian.ai/poojadas2014-pd/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "poojadas2014-pd/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/poojadas2014-pd/numpy-array-operations


'https://jovian.ai/poojadas2014-pd/numpy-array-operations'